[project]
name = "v6"
version = "0.1.0"
description = ""
authors = [
    {name = "vannda1",email = "vannda.it@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.139.2,<0.140.0)"
]

[tool.poetry]
packages = [{include = "v6", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
